export default {
    // regular: "Muli-Regular",
    // semiBold: "Muli-SemiBold",
    // bold: "Muli-Bold",
    // italic: "Muli-Italic",
    icomoon:'icomoon',
    play:'play',
    playBold:'playBold',
    Aldrich:'Aldrich',
    callingCodeBold:'callingCodeBold',
    callingCode:'callingCode',
    PoppinsThin:'PoppinsThin',
    Poppins:'Poppins',
    PoppinsBold:'PoppinsBold',
    captionBold:'captionBold',
    caption:'caption',
    TitilliumWeb:'TitilliumWeb-Black',
    TitilliumWeb_Bold:'TitilliumWeb-Bold',
    TitilliumWeb_Italic:'TitilliumWeb-Italic',
  }
  