const images = {
  splash: require('../assets/splash.png'),
  logo: require('../assets/logo.png'),
  backgroundButton: require('../assets/backgroundButon.png'),
  backgroundButtonLong: require('../assets/backgroundButtonLong.png'),
  backgroundButtonMedium: require('../assets/backgroundButtonMedium.png'),
  backgroundBottomBar: require('../assets/backgroundBottomBar.png'),
  ic_tabHome: require('../assets/ic_tab_home.png'),
  ic_tabHome_active: require('../assets/ic_tabHome_active.png'),  
  ic_tabJog2e: require('../assets/ic_tabJog2e.png'),
  ic_tabJog2e_active: require('../assets/ic_tabJog2e_active.png'),
  ic_tabInventory: require('../assets/ic_tabInventory.png'),
  ic_tabInventory_active: require('../assets/ic_tabInventory_active.png'),
  ic_tabClub: require('../assets/ic_tabClub.png'),
  ic_tabClub_active: require('../assets/ic_tabClub_active.png'),
  ic_tabNews: require('../assets/ic_tabNews.png'),
  ic_tabNews_active: require('../assets/ic_tabNews_active.png'),
  ic_avatar_default: require('../assets/ic_user.png'),
<<<<<<< Updated upstream

=======
  background_home: require('../assets/backgroundHome.png'),
  ic_e: require('../assets/ic_e.png'),
  ic_bell: require('../assets/ic_bell.png'),
  ic_play: require('../assets/ic_play.png'),
  backgroundSneaker: require('../assets/backgroundsneaker.png'),
  Equipment_green: require('../assets/Equipment_green.png'),
  Equipment_yellow: require('../assets/Equipment_Yellow.png'),
  Equipment_blue: require('../assets/Equipment_blue.png'),
  ic_switch: require('../assets/Switch.png'),
  ic_down: require('../assets/ic_down.png'),
  ic_filter_active: require('../assets/ic_filter_active.png'),
  ic_search: require('../assets/ic_search.png'),
  ic_buttonPuple_active: require('../assets/ic_buttonPuple_active.png'),
  ic_buttonPuple: require('../assets/ic_buttonPuple.png'),
  frame_image: require('../assets/frame_Image.png'),
  ic_back: require('../assets/ic_back.png'),
  ic_back: require('../assets/ic_back.png'),
  frame_sneaker: require('../assets/frame_sneaker.png'),
  ic_powerPink: require('../assets/ic_powerPink.png'),
  ic_power_yellow: require('../assets/ic_power_yellow.png'),
  ic_power_green: require('../assets/ic_power_green.png'),
  Equipment_violet: require('../assets/Equipment_violet.png'),
  Equipment_red: require('../assets/Equipment_red.png'),
  ic_power: require('../assets/ic_power.png'),
  ic_star: require('../assets/ic_star.png'),
  ic_step: require('../assets/ic_step.png'),
  ic_trash: require('../assets/ic_trash.png'),
  background_notify_detail: require('../assets/background_notify_detail.png'),
  background_imageNotify: require('../assets/bg_imageNotify.png'),
  frame_top: require('../assets/frame_top.png'),
  frame_bottm: require('../assets/frame_bottom.png'),
  ic_right: require('../assets/ic_right.png'),
  ic_distance: require('../assets/ic_distance.png'),
  ic_ref: require('../assets/ic_ref.png'),
  ic_history: require('../assets/ic_history.png'),
  ic_tutorial: require('../assets/ic_tutarial.png'),
  ic_support: require('../assets/ic_support.png'),
  ic_version: require('../assets/ic_version.png'),
  backgroundInput: require('../assets/bg_input.png'),
  btn_purple: require('../assets/BtnPurple.png'),
  ic_changePass: require('../assets/ic_changePass.png'),
  ic_finger: require('../assets/ic_finger.png'),
  bg_empty_club: require('../assets/backgroundEmptyClub.png'),
  ic_emptyClub: require('../assets/ic_emptyClub.png'),
>>>>>>> Stashed changes
};
export default images;
